### ISSUE TITLE
why not check the number of queries in the parsing config directive phase?

### ISSUE THREAD

**Issue by aCayF** [calio/beanstalkd-nginx-module#1]
hi calio,
    currently this checking is issued in the content handler long after the parsing config directive phase, is it better or not to put this operation ahead?
    related source code https://github.com/calio/beanstalkd-nginx-module/blob/master/src/ngx_http_beanstalkd_handler.c#L104

**Comment by calio** [comment]
The short answer is yes. The initial design is to support multiple queries per location, but I think this has never been implemented. So I just simply disabled this feature. It do cause a little bit confusing. But since I didn't write anything about multiple queries per location in the document, I think nobody has ever written like this. If you want to fix it, the best way is to make it support multiple queries per location. This is what I intended to do when I first wrote this module.

**Comment by aCayF** [comment]
hi, calio
i think making it support multiple queries per location may will need a lot of work to do, so for just focusing on what i really want to tweak for this module, maybe i will leave it that way now :)
